// 3D model assets. THIS FILE IS REGENERATED by tools/gen-manifest.mjs —
// do not hand-edit entries. Missing entries fall back to procedural props.

export const MODEL_MANIFEST = {
  armchair: { url: '/models/armchair.glb' },
  croissant: { url: '/models/croissant.glb' },
  cup: { url: '/models/cup.glb' },
  espresso_machine: { url: '/models/espresso_machine.glb' },
  plant: { url: '/models/plant.glb' },
};

// attribution data lives in CREDITS.md
