// Recorded music playlists. THIS FILE IS REGENERATED by tools/gen-manifest.mjs.
// Attribution and license source URLs live in CREDITS.md.

export const MUSIC_MANIFEST = {
  goldenhour: [
    { id: 'airport-lounge', title: "Airport Lounge", artist: "Kevin MacLeod", url: '/music/airport-lounge.ogg', duration: 70 },
    { id: 'everything', title: "Everything You Ever Dreamed.", artist: "HoliznaCC0", url: '/music/everything.ogg', duration: 80 },
    { id: 'warm-fuzz', title: "Warm Fuzz (LoFi, Retro)", artist: "HoliznaCC0", url: '/music/warm-fuzz.ogg', duration: 80 },
  ],
  midnight: [
    { id: 'beyond-piano', title: "Beyond (Piano Edit)", artist: "Pablo Perez", url: '/music/beyond-piano.ogg', duration: 80 },
    { id: 'jazz-one', title: "1 (jazz)", artist: "HoliznaCC0", url: '/music/jazz-one.ogg', duration: 80 },
    { id: 'jazz-two', title: "2 (jazz)", artist: "HoliznaCC0", url: '/music/jazz-two.ogg', duration: 80 },
    { id: 'lobby-time', title: "Lobby Time", artist: "Kevin MacLeod", url: '/music/lobby-time.ogg', duration: 70 },
  ],
  roastery: [
    { id: 'bossa-antigua', title: "Bossa Antigua", artist: "Kevin MacLeod", url: '/music/bossa-antigua.ogg', duration: 70 },
    { id: 'busted-jazz', title: "Busted Jazz", artist: "HoliznaCC0", url: '/music/busted-jazz.ogg', duration: 80 },
    { id: 'cellar-door', title: "Cellar Door", artist: "HoliznaCC0", url: '/music/cellar-door.ogg', duration: 80 },
  ],
  terrace: [
    { id: 'airport-lounge', title: "Airport Lounge", artist: "Kevin MacLeod", url: '/music/airport-lounge.ogg', duration: 70 },
    { id: 'everything', title: "Everything You Ever Dreamed.", artist: "HoliznaCC0", url: '/music/everything.ogg', duration: 80 },
  ],
};
