// Recorded sound assets. THIS FILE IS REGENERATED by tools/gen-manifest.mjs
// after the asset-gathering step — edit gains/flags there, not here.
// `gain` is a per-asset level trim; `loop` marks ambience beds.
// Missing/undownloadable entries fall back to synthesis automatically.

export const SOUND_MANIFEST = {};

// attribution data lives in CREDITS.md
