// Recorded sound assets. THIS FILE IS REGENERATED by tools/gen-manifest.mjs
// after the asset-gathering step — do not hand-edit entries.
// Missing/undownloadable entries fall back to synthesis automatically.
// Levels are auto-normalized at load time (see soundLoader.js).

export const SOUND_MANIFEST = {
  carpass: { url: '/sounds/carpass.mp3', loop: false }, // 14s
  chatter: { url: '/sounds/chatter.mp3', loop: true }, // 0s
  chatter2: { url: '/sounds/chatter2.mp3', loop: true }, // 0s
  espresso: { url: '/sounds/espresso.mp3', loop: false }, // 10.9s
  footsteps: { url: '/sounds/footsteps.mp3', loop: false }, // 12s
  rain_window: { url: '/sounds/rain_window.mp3', loop: true }, // 0s
  steam_milk: { url: '/sounds/steam_milk.mp3', loop: false }, // 0s
  traffic_day: { url: '/sounds/traffic_day.mp3', loop: true }, // 0s
  traffic_night: { url: '/sounds/traffic_night.mp3', loop: true }, // 34s
};

// attribution data lives in CREDITS.md
