// Surface texture assets. THIS FILE IS REGENERATED by tools/gen-manifest.mjs —
// do not hand-edit entries.

export const TEXTURE_MANIFEST = {
  'floor_conc.jpg': '/textures/floor_conc.jpg',
  'floor_conc_n.jpg': '/textures/floor_conc_n.jpg',
  'floor_dark.jpg': '/textures/floor_dark.jpg',
  'floor_dark_n.jpg': '/textures/floor_dark_n.jpg',
  'floor_wood.jpg': '/textures/floor_wood.jpg',
  'floor_wood_n.jpg': '/textures/floor_wood_n.jpg',
  'floor_wood_r.jpg': '/textures/floor_wood_r.jpg',
  'wall_plaster.jpg': '/textures/wall_plaster.jpg',
  'wall_plaster_n.jpg': '/textures/wall_plaster_n.jpg',
  'wood_dark.jpg': '/textures/wood_dark.jpg',
  'wood_dark_n.jpg': '/textures/wood_dark_n.jpg',
};
